// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'ap-southeast-2',
  aws_content_delivery_bucket: '30022-frontend-20190829193242-hostingbucket-prod',
  aws_content_delivery_bucket_region: 'ap-southeast-2',
  aws_content_delivery_url: 'https://d3jn5vndw8drm9.cloudfront.net',
  aws_cognito_region: 'ap-southeast-2',
  aws_user_pools_id: 'ap-southeast-2_Jlon4B6xy',
  aws_user_pools_web_client_id: '18qa8ikoosdfeqhqqi8g4taemh',
  oauth: {}
};

export default awsmobile;
