// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:a592575e-ca6d-4d03-9c5e-19d0a1be0002",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_CDcovUBDq",
    "aws_user_pools_web_client_id": "5tpu9ns9ce19g5hjhf3canm08m",
    "oauth": {},
    "aws_content_delivery_bucket": "30022-frontend-20190805201455-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "ap-southeast-2",
    "aws_content_delivery_url": "https://d19g47p6hpfi1b.cloudfront.net"
};


export default awsmobile;
